apiVersion: v1
kind: Service # Defines the type of Kubernetes object, in this case, a Service.
metadata:
  name: client-node-port # The name of the Service, used to identify it within the cluster.
spec:
  type: NodePort # Specifies the type of Service. NodePort exposes the Service on a static port on each Node.
  ports:
    - port: 80 # The port on which the Service is exposed internally within the cluster.
      targetPort: 80 # The port on the Pod to which the Service routes traffic.
      nodePort: 31515 # The port on the Node that allows external access to the Service.
      # Explanation of ports:
      # - `port`: The port that other Services or Pods within the cluster use to communicate with this Service.
      # - `targetPort`: The port on the container (inside the Pod) that receives the traffic.
      # - `nodePort`: The port on the Node that external users can use to access the Service.
  selector:
    component: web # A label selector used to identify the Pods that this Service routes traffic to.
  # The selector matches the labels defined in the Pods' metadata to associate the Service with the correct Pods.
